/**
 * @file iris_fonts.h
 * @brief IRIS — Vision Co-Pilot · custom LVGL bitmap fonts (CP7, 2026-05-02)
 *
 * Generated by lv_font_conv from:
 *   - Space Grotesk Variable (sliced into static Regular/SemiBold/Bold)
 *   - JetBrains Mono Regular
 *
 * All fonts are 4bpp antialiased. Glyph ranges:
 *   ASCII (0x20-0x7F), Latin-1 supplement (0xA0-0xFF),
 *   selected punctuation (em dash, ellipsis, arrows),
 *   geometric shapes (▲ ● ▼ — JetBrains Mono fonts only)
 *
 * Source TTFs in fonts/src/, generator script at fonts/gen_fonts.sh.
 * Do NOT hand-edit the .c files in fonts/generated/ — regenerate from source.
 */
#ifndef __IRIS_FONTS_H__
#define __IRIS_FONTS_H__

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Display sans (Space Grotesk) */
extern const lv_font_t font_iris_hero_44;     /* Bold      — speak action line */
extern const lv_font_t font_iris_title_32;    /* SemiBold  — boot title, mode banner */
extern const lv_font_t font_iris_status_24;   /* SemiBold  — status / CTA */
extern const lv_font_t font_iris_body_16;     /* Regular   — body / response */

/* Programmer mono (JetBrains Mono) */
extern const lv_font_t font_iris_mono_sm_12;  /* Regular   — tag labels */
extern const lv_font_t font_iris_mono_xs_10;  /* Regular   — micro labels */

/* Icon font (JetBrains Mono 24pt — only for arrow / dot glyphs) */
extern const lv_font_t font_iris_icons_24;

/* UTF-8 byte literals — match codepoints baked in the fonts above. */
#define IRIS_GLYPH_UP        "\xE2\x96\xB2"  /* U+25B2 ▲ */
#define IRIS_GLYPH_DOWN      "\xE2\x96\xBC"  /* U+25BC ▼ */
#define IRIS_GLYPH_DOT       "\xE2\x97\x8F"  /* U+25CF ● */
#define IRIS_GLYPH_MIDDOT    "\xC2\xB7"      /* U+00B7 · — separator */
#define IRIS_GLYPH_RARROW    "\xE2\x86\x92"  /* U+2192 → */
#define IRIS_GLYPH_LARROW    "\xE2\x86\x90"  /* U+2190 ← */
#define IRIS_GLYPH_EMDASH    "\xE2\x80\x94"  /* U+2014 — */
#define IRIS_GLYPH_HELLIP    "\xE2\x80\xA6"  /* U+2026 … */

#ifdef __cplusplus
}
#endif

#endif /* __IRIS_FONTS_H__ */
